version: "3.7"
services:
  db:
    image: "mariadb:10.3"
    container_name: app-db
    restart: unless-stopped
    ports:
     - "3334:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  app:
    build:
      args:
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: app-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
   
  nginx:
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8092:80
    build:
        context: ./
        dockerfile: docker-compose/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/

  miner:
    container_name: app-miner
    restart: on-failure
    ports:
    # - 5000:5001
    build:
        context: ./
        dockerfile: docker-compose/miner/Dockerfile
    volumes:
      - ./docker-compose/miner/:/opt
   