version: "3.7"
services:
  
  db:
    container_name: app-db
    restart: unless-stopped
    ports:
     - "3334:3306"
    build:
      context: ./
      dockerfile: docker-compose/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    # networks:
    #   - towers

  app:
    build:
      args:
        user: duncan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: towers
    container_name: app-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    # networks:
    #   - towers
  
  nginx:
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8092:80
    build:
        context: ./
        dockerfile: docker-compose/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    # networks:
    #   - towers

# networks:
#   towers:
#     driver: bridge
